# Generated by Django 3.1 on 2020-08-26 16:50

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(default='')),
                ('value', models.TextField(default=common.models.getDefaultValue, primary_key=True, serialize=False)),
            ],
        ),
    ]
