# Generated by Django 3.1 on 2020-08-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='name',
        ),
    ]
