# Generated by Django 3.1 on 2020-08-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200827_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
